/**
 * Created by Kelvin Ishigo on 10/1/17.
 *
 * Copyright (c) 2017 Kelvin Ishigo
 * Licensed under the MIT License. See LICENSE file in the project root for full license information.
 */
// Types specific to recipe SPA...Convention is to work verb + object
export const RecipeTypes = {
	INGEST_RECIPE: 'INGEST_RECIPE',
	DELETE_RECIPE: 'DELETE_RECIPE',
	FILTER_RECIPE: 'FILTER_RECIPE',
	MODIFY_RECIPE: 'MODIFY_RECIPE',
	DISPLAY_RECIPE: 'DISPLAY_RECIPE',
	HIGHLIGHT_RECIPE: 'HIGHLIGHT_RECIPE'
};
/**
 * Important that strings must be unique across all <action>Types
 * @type {{ADD_ITEM: string, DELETE_ITEM: string, DELETE_COMPLETED_ITEMS: string, COMPLETE_ITEM: string}}
 */
export const ShoppingTypes = {
	ADD_ITEM: 'ADD_SHOPPING_ITEM',
	DELETE_ITEM: 'DELETE_SHOPPING_ITEM',
	CLEAR_LIST: 'CLEAR_SHOPPING_LIST',
	SHOW_ALL: 'SHOW_ALL_SHOPPING_ITEMS',
	SHOW_ACTIVE: 'SHOW_ACTIVE_SHOPPING_ITEMS',
	SHOW_COMPLETED: 'SHOW_COMPLETED_SHOPPING_ITEMS',
	DELETE_COMPLETED_ITEMS: 'DELETE_COMPLETED_SHOPPING_ITEMS',
	COMPLETE_ITEM: 'COMPLETE_SHOPPING_ITEM',
	SET_VISIBILITY_FILTER: 'SET_SHOPPING_VISIBILITY_FILTER'
};

export const IngredientTypes = {
	ADD_ITEM: 'ADD_INGREDIENT_ITEM',
	DELETE_ITEM: 'DELETE_INGREDIENT_ITEM',
	CLEAR_LIST: 'CLEAR_INGREDIENT_LIST',
	SHOW_ALL: 'SHOW_ALL_INGREDIENT_ITEMS',
	SHOW_ACTIVE: 'SHOW_ACTIVE_INGREDIENT_ITEMS',
	SHOW_COMPLETED: 'SHOW_COMPLETED_INGREDIENT_ITEMS',
	COMPLETE_ITEM: 'COMPLETE_INGREDIENT_ITEM',
	SET_VISIBILITY_FILTER: 'SET_INGREDIENT_VISIBILITY_FILTER'
};

export const  TestNewTypes = {
	OPEN_HERO_CONTAINER: 'OPEN_HERO_CONTAINER',
	CLOSE_HERO_CONTAINER: 'CLOSE_HERO_CONTAINER',
	UPDATE_HERO_CONTAINER: 'UPDATE_HERO_CONTAINER',
};